version: '3.1'

services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_BASICAUTH_USERNAME: rootuser
        ME_CONFIG_BASICAUTH_PASSWORD: rootpass
        #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
        ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
        ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@10.10.9.10:27017/myFirstDatabase?authSource=admin 
      depends_on:
        - mongo

volumes:
        mongodb_data_container: